#
# replace 'sr' with your initials
#
# curl 'https://raw.githubusercontent.com/remstef/webanno-exmaralda/master/docker-compose.yml' | docker-compose -f - -p sr up
#
# docker-compose -p sr up -d
#
# or
#
# docker-compose -p sr up
#
# docker-compose -p sr down
#
# roughly resembles:
#    $ docker run --name webanno-mysql -v $WEBANNO_HOME/mysql:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=toor -e MYSQL_USER=webanno -e MYSQL_PASSWORD=webanno -e MYSQL_DATABASE=webanno -p 3306:3306 -d mysql:5 --character-set-server=utf8 --collation-server=utf8_bin
#    $ docker run -d --name webanno-server -p 18080:18080 --link webanno-mysql:mysql webanno-server
#
version: '3'

networks:
  webanno-net:

services:
  webanno-mysql:
    image: "mysql:5"
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=webanno
      - MYSQL_USER=webanno
      - MYSQL_PORT=3306
      - MYSQL_PASSWORD=webanno
    volumes:
      - ${WEBANNO_HOME}/mysql-data:/var/lib/mysql
    command: ["--character-set-server=utf8", "--collation-server=utf8_bin"]
    healthcheck:
      test: ["CMD", "mysql", "-uwebanno", "-pwebanno", "-D", "webanno", "-e 'SELECT 1;'" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      webanno-net:
        aliases:
          - mysql

  webanno-server:
#    build:
#      context: ./
#      dockerfile: Dockerfile
    image: "remstef/webanno-exmaralda:latest"
    environment:
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
    ports:
      - "18080:18080"
    depends_on:
      - webanno-mysql
    restart: unless-stopped
    networks:
      webanno-net:
